const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const rect = figma.createRectangle();
rect.resize(220, 120);
rect.x = 130;
rect.y = 120;
rect.cornerRadius = 24;
rect.topLeftRadius = 40;
rect.topRightRadius = 8;
rect.bottomRightRadius = 40;
rect.bottomLeftRadius = 8;
rect.fills = [{ type: 'SOLID', color: { r: 0.15, g: 0.55, b: 0.95 } }];
root.appendChild(rect);
return { rootId: root.id };
