const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const row = figma.createAutoLayout();
row.resize(280, 120);
row.x = 100;
row.y = 120;
row.itemSpacing = 24;
const poly = figma.createPolygon();
poly.pointCount = 6;
poly.resize(100, 100);
poly.fills = [{ type: 'SOLID', color: { r: 0.5, g: 0.25, b: 0.85 } }];
const star = figma.createStar();
star.pointCount = 5;
star.innerRadius = 0.45;
star.resize(100, 100);
star.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.75, b: 0.1 } }];
row.appendChild(poly);
row.appendChild(star);
root.appendChild(row);
return { rootId: root.id };
