await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.98, g: 0.98, b: 1 } }];
figma.currentPage.appendChild(root);
const panel = figma.createFrame();
panel.resize(320, 240);
panel.x = 80;
panel.y = 60;
panel.cornerRadius = 10;
panel.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
panel.strokes = [{ type: 'SOLID', color: { r: 0.88, g: 0.9, b: 0.94 } }];
panel.strokeWeight = 1;
root.appendChild(panel);
const title = figma.createText();
title.characters = 'Release notes';
title.fontSize = 18;
title.lineHeight = { unit: 'PIXELS', value: 26 };
title.letterSpacing = { unit: 'PERCENT', value: -2 };
title.x = 16;
title.y = 16;
panel.appendChild(title);
const body = figma.createText();
body.characters = 'Ship dark mode\nPolish onboarding\nFix grid gaps';
body.fontSize = 13;
body.lineHeight = { unit: 'PIXELS', value: 20 };
body.paragraphSpacing = 10;
body.listOptions = { type: 'ORDERED' };
body.x = 16;
body.y = 52;
body.resize(288, 160);
panel.appendChild(body);
return { rootId: root.id };
