await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
function createAutoLayout(direction) {
  if (typeof figma.createAutoLayout === 'function') {
    return figma.createAutoLayout(direction);
  }
  const frame = figma.createFrame();
  frame.layoutMode = direction === 'VERTICAL' ? 'VERTICAL' : 'HORIZONTAL';
  return frame;
}
const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const split = createAutoLayout('HORIZONTAL');
split.resize(440, 312);
split.x = 20;
split.y = 24;
split.itemSpacing = 0;
const list = createAutoLayout('VERTICAL');
list.resize(188, 312);
list.paddingTop = 12;
list.paddingLeft = 10;
list.paddingRight = 10;
list.paddingBottom = 12;
list.itemSpacing = 8;
list.cornerRadius = 14;
list.fills = [{ type: 'SOLID', color: { r: 0.97, g: 0.98, b: 1 } }];
list.strokes = [{ type: 'SOLID', color: { r: 0.88, g: 0.9, b: 0.93 } }];
list.strokeWeight = 1;
function thread(sel, unread, who, sub, prev) {
  const row = createAutoLayout('HORIZONTAL');
  row.resize(168, 56);
  row.paddingLeft = 8;
  row.paddingRight = 8;
  row.paddingTop = 8;
  row.paddingBottom = 8;
  row.itemSpacing = 8;
  row.cornerRadius = 12;
  row.counterAxisAlignItems = 'CENTER';
  row.fills = sel ? [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }] : [];
  row.effects = sel ? [{ type: 'DROP_SHADOW', color: { r: 0, g: 0, b: 0, a: 0.08 }, offset: { x: 0, y: 4 }, radius: 10, blendMode: 'NORMAL', visible: true }] : [];
  if (sel) {
    row.strokes = [{ type: 'SOLID', color: { r: 0.2, g: 0.45, b: 0.95 } }];
    row.strokeWeight = 1;
  }
  const av = figma.createEllipse();
  av.resize(36, 36);
  av.fills = [{ type: 'SOLID', color: { r: 0.75, g: 0.82, b: 0.94 } }];
  const mid = createAutoLayout('VERTICAL');
  mid.resize(96, 40);
  mid.itemSpacing = 3;
  const w = figma.createText();
  w.characters = who;
  w.fontSize = 11;
  w.fills = [{ type: 'SOLID', color: { r: 0.12, g: 0.14, b: 0.2 } }];
  const s = figma.createText();
  s.characters = sub;
  s.fontSize = 10;
  s.fills = [{ type: 'SOLID', color: { r: 0.35, g: 0.38, b: 0.45 } }];
  const p = figma.createText();
  p.characters = prev;
  p.fontSize = 9;
  p.fills = [{ type: 'SOLID', color: { r: 0.55, g: 0.56, b: 0.62 } }];
  mid.appendChild(w);
  mid.appendChild(s);
  mid.appendChild(p);
  row.appendChild(av);
  row.appendChild(mid);
  if (unread) {
    const dot = figma.createEllipse();
    dot.resize(8, 8);
    dot.fills = [{ type: 'SOLID', color: { r: 0.2, g: 0.45, b: 0.98 } }];
    row.appendChild(dot);
  }
  return row;
}
list.appendChild(thread(true, false, 'Sasha', 'Re: Launch checklist', 'Let us lock assets by Friday'));
list.appendChild(thread(false, true, 'Finance bot', 'Invoice #4421', 'Payment scheduled'));
list.appendChild(thread(false, true, 'Ops', 'Latency report', 'p95 down to 180ms'));
split.appendChild(list);
const reader = createAutoLayout('VERTICAL');
reader.resize(252, 312);
reader.paddingTop = 16;
reader.paddingLeft = 16;
reader.paddingRight = 16;
reader.paddingBottom = 16;
reader.itemSpacing = 12;
reader.cornerRadius = 14;
reader.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
reader.strokes = [{ type: 'SOLID', color: { r: 0.88, g: 0.9, b: 0.93 } }];
reader.strokeWeight = 1;
const meta = createAutoLayout('HORIZONTAL');
meta.resize(220, 40);
meta.primaryAxisAlignItems = 'SPACE_BETWEEN';
meta.counterAxisAlignItems = 'CENTER';
const who2 = figma.createText();
who2.characters = 'Sasha Ibrahim';
who2.fontSize = 14;
who2.fills = [{ type: 'SOLID', color: { r: 0.08, g: 0.09, b: 0.14 } }];
const when = figma.createText();
when.characters = 'Today · 9:42 AM';
when.fontSize = 10;
when.fills = [{ type: 'SOLID', color: { r: 0.48, g: 0.5, b: 0.56 } }];
meta.appendChild(who2);
meta.appendChild(when);
reader.appendChild(meta);
const subj = figma.createText();
subj.characters = 'Re: Launch checklist — assets + QA';
subj.fontSize = 15;
subj.fills = [{ type: 'SOLID', color: { r: 0.12, g: 0.14, b: 0.2 } }];
reader.appendChild(subj);
const p1 = figma.createText();
p1.characters = 'Hey team — pushing the hero swaps tonight. Need sign-off on tokens before we cut RC2.';
p1.fontSize = 11;
p1.fills = [{ type: 'SOLID', color: { r: 0.28, g: 0.3, b: 0.36 } }];
const p2 = figma.createText();
p2.characters = 'Can someone snapshot the dashboard dark mode regression pack? I will attach figures in thread.';
p2.fontSize = 11;
p2.fills = [{ type: 'SOLID', color: { r: 0.28, g: 0.3, b: 0.36 } }];
reader.appendChild(p1);
reader.appendChild(p2);
const actions = createAutoLayout('HORIZONTAL');
actions.itemSpacing = 10;
const reply = figma.createRectangle();
reply.resize(76, 30);
reply.cornerRadius = 8;
reply.fills = [{ type: 'SOLID', color: { r: 0.14, g: 0.38, b: 0.95 } }];
const fwd = figma.createRectangle();
fwd.resize(76, 30);
fwd.cornerRadius = 8;
fwd.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
fwd.strokes = [{ type: 'SOLID', color: { r: 0.86, g: 0.88, b: 0.92 } }];
fwd.strokeWeight = 1;
actions.appendChild(reply);
actions.appendChild(fwd);
reader.appendChild(actions);
split.appendChild(reader);
root.appendChild(split);
return { rootId: root.id };
