const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const rect = figma.createRectangle();
rect.resize(240, 140);
rect.x = 120;
rect.y = 110;
rect.fills = [];
rect.strokes = [{ type: 'SOLID', color: { r: 0.1, g: 0.1, b: 0.1 } }];
rect.strokeWeight = 3;
rect.dashPattern = [8, 6];
root.appendChild(rect);
return { rootId: root.id };
