const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const row = figma.createAutoLayout();
row.resize(360, 48);
row.x = 60;
row.y = 156;
row.itemSpacing = 12;
const a = figma.createRectangle();
a.resize(80, 36);
a.fills = [{ type: 'SOLID', color: { r: 0.2, g: 0.6, b: 0.9 } }];
const ghost = figma.createRectangle();
ghost.resize(80, 36);
ghost.fills = [{ type: 'SOLID', color: { r: 0.9, g: 0.2, b: 0.2 } }];
ghost.opacity = 0;
const b = figma.createRectangle();
b.resize(80, 36);
b.fills = [{ type: 'SOLID', color: { r: 0.2, g: 0.75, b: 0.35 } }];
row.appendChild(a);
row.appendChild(ghost);
row.appendChild(b);
root.appendChild(row);
return { rootId: root.id };
