const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const col = figma.variables.createVariableCollection('Theme');
const lightId = col.modes[0].id;
const darkId = col.addMode('Dark');
const theme = figma.variables.createVariable('bg', col, 'COLOR');
figma.variables.setValueForMode(theme.id, lightId, { type: 'COLOR', color: { r: 0.95, g: 0.96, b: 0.98 } });
figma.variables.setValueForMode(theme.id, darkId, { type: 'COLOR', color: { r: 0.1, g: 0.15, b: 0.35 } });
figma.variables.setVariableCollectionActiveMode(col, darkId);
const rect = figma.createRectangle();
rect.resize(280, 180);
rect.x = 100;
rect.y = 90;
root.appendChild(rect);
rect.setBoundVariable('fills', theme);
return { rootId: root.id };
