await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
function createAutoLayout(direction) {
  if (typeof figma.createAutoLayout === 'function') {
    return figma.createAutoLayout(direction);
  }
  const frame = figma.createFrame();
  frame.layoutMode = direction === 'VERTICAL' ? 'VERTICAL' : 'HORIZONTAL';
  return frame;
}
const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const card = createAutoLayout('VERTICAL');
card.resize(400, 312);
card.x = 40;
card.y = 24;
card.cornerRadius = 18;
card.clipsContent = true;
card.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
card.effects = [{ type: 'DROP_SHADOW', color: { r: 0.2, g: 0.25, b: 0.4, a: 0.14 }, offset: { x: 0, y: 10 }, radius: 22, blendMode: 'NORMAL', visible: true }];
const hero = figma.createRectangle();
hero.resize(400, 120);
hero.fills = [{ type: 'GRADIENT_LINEAR', gradientStops: [{ position: 0, color: { r: 0.65, g: 0.78, b: 1, a: 1 } }, { position: 1, color: { r: 0.82, g: 0.7, b: 1, a: 1 } }], gradientTransform: [[1, 0, 0], [0, 1, 0]] }];
card.appendChild(hero);
const avatarWrap = figma.createFrame();
avatarWrap.resize(88, 88);
avatarWrap.x = 156;
avatarWrap.y = 76;
avatarWrap.fills = [];
const ring = figma.createEllipse();
ring.resize(88, 88);
ring.fills = [];
ring.strokes = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
ring.strokeWeight = 4;
const face = figma.createEllipse();
face.resize(72, 72);
face.x = 8;
face.y = 8;
face.fills = [{ type: 'SOLID', color: { r: 0.55, g: 0.72, b: 0.9 } }];
avatarWrap.appendChild(ring);
avatarWrap.appendChild(face);
card.appendChild(avatarWrap);
const body = createAutoLayout('VERTICAL');
body.resize(400, 200);
body.y = 164;
body.paddingTop = 20;
body.paddingLeft = 24;
body.paddingRight = 24;
body.itemSpacing = 12;
body.primaryAxisAlignItems = 'CENTER';
body.counterAxisAlignItems = 'CENTER';
const name = figma.createText();
name.characters = 'Mira Chen';
name.fontSize = 20;
name.fills = [{ type: 'SOLID', color: { r: 0.07, g: 0.08, b: 0.12 } }];
const handle = figma.createText();
handle.characters = '@mchen · Product Design';
handle.fontSize = 11;
handle.fills = [{ type: 'SOLID', color: { r: 0.45, g: 0.48, b: 0.55 } }];
body.appendChild(name);
body.appendChild(handle);
const stats = createAutoLayout('HORIZONTAL');
stats.itemSpacing = 18;
stats.paddingTop = 4;
function statBlock(n, lab) {
  const col = createAutoLayout('VERTICAL');
  col.itemSpacing = 2;
  col.primaryAxisAlignItems = 'CENTER';
  const nv = figma.createText();
  nv.characters = n;
  nv.fontSize = 16;
  nv.fills = [{ type: 'SOLID', color: { r: 0.12, g: 0.45, b: 0.9 } }];
  const lb = figma.createText();
  lb.characters = lab;
  lb.fontSize = 10;
  lb.fills = [{ type: 'SOLID', color: { r: 0.5, g: 0.52, b: 0.58 } }];
  col.appendChild(nv);
  col.appendChild(lb);
  return col;
}
stats.appendChild(statBlock('128', 'Projects'));
stats.appendChild(statBlock('14k', 'Followers'));
stats.appendChild(statBlock('96%', 'Response'));
body.appendChild(stats);
const chips = createAutoLayout('HORIZONTAL');
chips.itemSpacing = 8;
chips.paddingTop = 4;
function chip(txt) {
  const c = createAutoLayout('HORIZONTAL');
  c.paddingLeft = 10;
  c.paddingRight = 10;
  c.paddingTop = 5;
  c.paddingBottom = 5;
  c.cornerRadius = 14;
  c.counterAxisAlignItems = 'CENTER';
  c.fills = [{ type: 'SOLID', color: { r: 0.94, g: 0.95, b: 0.99 } }];
  const t = figma.createText();
  t.characters = txt;
  t.fontSize = 10;
  t.fills = [{ type: 'SOLID', color: { r: 0.32, g: 0.35, b: 0.45 } }];
  c.appendChild(t);
  return c;
}
chips.appendChild(chip('Design systems'));
chips.appendChild(chip('Prototyping'));
chips.appendChild(chip('Tokyo'));
body.appendChild(chips);
card.appendChild(body);
root.appendChild(card);
return { rootId: root.id };
