const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const sq = figma.createRectangle();
sq.resize(120, 120);
sq.x = 150;
sq.y = 120;
sq.fills = [{ type: 'SOLID', color: { r: 0.2, g: 0.5, b: 0.9 } }];
root.appendChild(sq);
const circ = figma.createEllipse();
circ.resize(120, 120);
circ.x = 210;
circ.y = 120;
circ.fills = [{ type: 'SOLID', color: { r: 0.2, g: 0.5, b: 0.9 } }];
root.appendChild(circ);
figma.intersect([sq, circ], root);
return { rootId: root.id };
