const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
root.clipsContent = true;
const content = figma.createRectangle();
content.resize(300, 200);
content.x = 200;
content.y = 100;
content.fills = [{ type: 'SOLID', color: { r: 0.2, g: 0.65, b: 0.4 } }];
root.appendChild(content);
const mask = figma.createRectangle();
mask.resize(200, 200);
mask.x = 140;
mask.y = 80;
mask.cornerRadius = 100;
mask.isMask = true;
mask.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
root.appendChild(mask);
return { rootId: root.id };
