const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const rect = figma.createRectangle();
rect.resize(120, 120);
rect.x = 180;
rect.y = 120;
rect.rotation = 45;
rect.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.55, b: 0.1 } }];
root.appendChild(rect);
return { rootId: root.id };
