const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const bg = figma.createRectangle();
bg.resize(480, 360);
bg.fills = [{ type: 'SOLID', color: { r: 0.2, g: 0.5, b: 0.85 } }];
root.appendChild(bg);
const noFill = figma.createRectangle();
noFill.resize(180, 100);
noFill.x = 60;
noFill.y = 130;
noFill.fills = [];
noFill.strokes = [{ type: 'SOLID', color: { r: 0, g: 0, b: 0 } }];
noFill.strokeWeight = 2;
root.appendChild(noFill);
const semi = figma.createRectangle();
semi.resize(180, 100);
semi.x = 260;
semi.y = 130;
semi.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1, a: 0.4 } }];
root.appendChild(semi);
return { rootId: root.id };
