const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const a = figma.createRectangle();
a.resize(60, 60);
a.fills = [{ type: 'SOLID', color: { r: 0.9, g: 0.2, b: 0.2 } }];
root.appendChild(a);
const b = figma.createRectangle();
b.resize(60, 60);
b.x = 40;
b.y = 40;
b.fills = [{ type: 'SOLID', color: { r: 0.2, g: 0.7, b: 0.3 } }];
root.appendChild(b);
const tg = figma.transformGroup([a, b], root);
tg.x = 180;
tg.y = 120;
tg.rotation = 20;
return { rootId: root.id };
