await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
function createAutoLayout(direction) {
  if (typeof figma.createAutoLayout === 'function') {
    return figma.createAutoLayout(direction);
  }
  const frame = figma.createFrame();
  frame.layoutMode = direction === 'VERTICAL' ? 'VERTICAL' : 'HORIZONTAL';
  return frame;
}
const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const col = figma.variables.createVariableCollection('Settings');
const modeId = col.modes[0].modeId;
const accent = figma.variables.createVariable('accent', col, 'COLOR');
accent.setValueForMode(modeId, { r: 0.2, g: 0.48, b: 0.95 });
const railBg = figma.variables.createVariable('rail', col, 'COLOR');
railBg.setValueForMode(modeId, { r: 0.97, g: 0.97, b: 0.99 });
const shell = createAutoLayout('HORIZONTAL');
shell.resize(440, 318);
shell.x = 20;
shell.y = 21;
shell.itemSpacing = 12;
const rail = createAutoLayout('VERTICAL');
rail.resize(112, 318);
rail.paddingTop = 14;
rail.paddingLeft = 10;
rail.paddingRight = 10;
rail.paddingBottom = 12;
rail.itemSpacing = 6;
rail.cornerRadius = 14;
rail.fills = [figma.variables.setBoundVariableForPaint({ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }, 'color', railBg)];
rail.strokes = [{ type: 'SOLID', color: { r: 0.86, g: 0.89, b: 0.93 } }];
rail.strokeWeight = 1;
function navRow(label, active) {
  const row = createAutoLayout('HORIZONTAL');
  row.resize(92, 34);
  row.paddingLeft = 10;
  row.paddingRight = 10;
  row.cornerRadius = 9;
  row.counterAxisAlignItems = 'CENTER';
  if (active) {
    row.fills = [{ type: 'SOLID', color: { r: 0.9, g: 0.95, b: 1 } }];
  }
  const t = figma.createText();
  t.characters = label;
  t.fontSize = 11;
  t.fills = [{ type: 'SOLID', color: active ? { r: 0.12, g: 0.35, b: 0.88 } : { r: 0.38, g: 0.4, b: 0.48 } }];
  row.appendChild(t);
  return row;
}
rail.appendChild(navRow('General', true));
rail.appendChild(navRow('Team', false));
rail.appendChild(navRow('Billing', false));
rail.appendChild(navRow('Notifications', false));
const pane = createAutoLayout('VERTICAL');
pane.resize(316, 318);
pane.paddingTop = 16;
pane.paddingLeft = 18;
pane.paddingRight = 18;
pane.paddingBottom = 14;
pane.itemSpacing = 14;
pane.cornerRadius = 14;
pane.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
pane.strokes = [{ type: 'SOLID', color: { r: 0.86, g: 0.89, b: 0.93 } }];
pane.strokeWeight = 1;
const h1 = figma.createText();
h1.characters = 'Workspace defaults';
h1.fontSize = 18;
h1.fills = [{ type: 'SOLID', color: { r: 0.08, g: 0.1, b: 0.14 } }];
pane.appendChild(h1);
const lead = figma.createText();
lead.characters = 'Org-wide rules for libraries, exports, and review flows.';
lead.fontSize = 11;
lead.fills = [{ type: 'SOLID', color: { r: 0.42, g: 0.45, b: 0.52 } }];
pane.appendChild(lead);
const rule = figma.createRectangle();
rule.resize(268, 1);
rule.fills = [{ type: 'SOLID', color: { r: 0.91, g: 0.92, b: 0.95 } }];
pane.appendChild(rule);
const rowToggle = createAutoLayout('HORIZONTAL');
rowToggle.resize(280, 44);
rowToggle.primaryAxisAlignItems = 'SPACE_BETWEEN';
rowToggle.counterAxisAlignItems = 'CENTER';
const stack = createAutoLayout('VERTICAL');
stack.itemSpacing = 3;
const a = figma.createText();
a.characters = 'Auto-save version history';
a.fontSize = 12;
a.fills = [{ type: 'SOLID', color: { r: 0.14, g: 0.15, b: 0.2 } }];
const b = figma.createText();
b.characters = 'Capture checkpoints while editors are open';
b.fontSize = 10;
b.fills = [{ type: 'SOLID', color: { r: 0.48, g: 0.5, b: 0.56 } }];
stack.appendChild(a);
stack.appendChild(b);
const cap = figma.createFrame();
cap.resize(52, 28);
cap.fills = [];
const track = figma.createRectangle();
track.resize(46, 22);
track.x = 3;
track.y = 3;
track.cornerRadius = 11;
track.fills = [figma.variables.setBoundVariableForPaint({ type: 'SOLID', color: { r: 0, g: 0, b: 0 } }, 'color', accent)];
const knob = figma.createEllipse();
knob.resize(18, 18);
knob.x = 28;
knob.y = 5;
knob.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
cap.appendChild(track);
cap.appendChild(knob);
rowToggle.appendChild(stack);
rowToggle.appendChild(cap);
pane.appendChild(rowToggle);
const row2 = createAutoLayout('HORIZONTAL');
row2.resize(280, 40);
row2.primaryAxisAlignItems = 'SPACE_BETWEEN';
row2.counterAxisAlignItems = 'CENTER';
row2.cornerRadius = 10;
row2.paddingLeft = 12;
row2.paddingRight = 12;
row2.fills = [{ type: 'SOLID', color: { r: 0.97, g: 0.98, b: 0.99 } }];
const l2 = figma.createText();
l2.characters = 'Default review branch';
l2.fontSize = 12;
l2.fills = [{ type: 'SOLID', color: { r: 0.18, g: 0.18, b: 0.22 } }];
const chev = figma.createText();
chev.characters = 'main  ›';
chev.fontSize = 12;
chev.fills = [{ type: 'SOLID', color: { r: 0.45, g: 0.48, b: 0.55 } }];
row2.appendChild(l2);
row2.appendChild(chev);
pane.appendChild(row2);
shell.appendChild(rail);
shell.appendChild(pane);
root.appendChild(shell);
return { rootId: root.id };
