await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const btnFrame = figma.createFrame();
btnFrame.resize(72, 28);
btnFrame.fills = [{ type: 'SOLID', color: { r: 0.15, g: 0.45, b: 0.95 } }];
figma.currentPage.appendChild(btnFrame);
const btnComp = figma.createComponentFromNode(btnFrame);
const cardFrame = figma.createFrame();
cardFrame.resize(200, 100);
cardFrame.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
const btnInst = figma.createComponentInstance(btnComp.id);
btnInst.x = 64;
btnInst.y = 36;
cardFrame.appendChild(btnInst);
figma.currentPage.appendChild(cardFrame);
const cardComp = figma.createComponentFromNode(cardFrame);
const cardInst = figma.createComponentInstance(cardComp.id);
cardInst.x = 140;
cardInst.y = 130;
root.appendChild(cardInst);
return { rootId: root.id };
