await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
function createAutoLayout(direction) {
  if (typeof figma.createAutoLayout === 'function') {
    return figma.createAutoLayout(direction);
  }
  const frame = figma.createFrame();
  frame.layoutMode = direction === 'VERTICAL' ? 'VERTICAL' : 'HORIZONTAL';
  return frame;
}
const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const page = createAutoLayout('VERTICAL');
page.resize(432, 328);
page.x = 24;
page.y = 18;
page.itemSpacing = 12;
const hero = createAutoLayout('HORIZONTAL');
hero.resize(432, 56);
hero.paddingLeft = 14;
hero.paddingRight = 14;
hero.cornerRadius = 12;
hero.counterAxisAlignItems = 'CENTER';
hero.itemSpacing = 12;
hero.fills = [{ type: 'GRADIENT_LINEAR', gradientStops: [{ position: 0, color: { r: 0.12, g: 0.18, b: 0.42, a: 1 } }, { position: 1, color: { r: 0.32, g: 0.22, b: 0.55, a: 1 } }], gradientTransform: [[1, 0, 0], [0, 1, 0]] }];
const bag = figma.createText();
bag.characters = 'Secure checkout';
bag.fontSize = 16;
bag.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
const subhero = figma.createText();
subhero.characters = 'Order ORD-9182';
subhero.fontSize = 11;
subhero.fills = [{ type: 'SOLID', color: { r: 0.82, g: 0.86, b: 0.95, a: 1 } }];
const heroStack = createAutoLayout('VERTICAL');
heroStack.itemSpacing = 2;
heroStack.appendChild(bag);
heroStack.appendChild(subhero);
hero.appendChild(heroStack);
page.appendChild(hero);
function line(title, price) {
  const row = createAutoLayout('HORIZONTAL');
  row.resize(408, 52);
  row.primaryAxisAlignItems = 'SPACE_BETWEEN';
  row.counterAxisAlignItems = 'CENTER';
  row.paddingLeft = 10;
  row.paddingRight = 10;
  row.cornerRadius = 10;
  row.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
  row.strokes = [{ type: 'SOLID', color: { r: 0.9, g: 0.91, b: 0.94 } }];
  row.strokeWeight = 1;
  const left = createAutoLayout('HORIZONTAL');
  left.itemSpacing = 10;
  left.counterAxisAlignItems = 'CENTER';
  const thumb = figma.createRectangle();
  thumb.resize(40, 40);
  thumb.cornerRadius = 8;
  thumb.fills = [{ type: 'SOLID', color: { r: 0.88, g: 0.9, b: 0.96 } }];
  const v = createAutoLayout('VERTICAL');
  v.itemSpacing = 3;
  const t1 = figma.createText();
  t1.characters = title;
  t1.fontSize = 12;
  t1.fills = [{ type: 'SOLID', color: { r: 0.12, g: 0.13, b: 0.18 } }];
  const t2 = figma.createText();
  t2.characters = 'Qty 1 · Digital';
  t2.fontSize = 10;
  t2.fills = [{ type: 'SOLID', color: { r: 0.48, g: 0.5, b: 0.56 } }];
  v.appendChild(t1);
  v.appendChild(t2);
  left.appendChild(thumb);
  left.appendChild(v);
  const pr = figma.createText();
  pr.characters = price;
  pr.fontSize = 13;
  pr.fills = [{ type: 'SOLID', color: { r: 0.1, g: 0.1, b: 0.14 } }];
  row.appendChild(left);
  row.appendChild(pr);
  return row;
}
page.appendChild(line('Pro workspace (annual)', '$228.00'));
page.appendChild(line('Brand kit add-on', '$48.00'));
const promo = createAutoLayout('HORIZONTAL');
promo.resize(408, 38);
promo.paddingLeft = 10;
promo.paddingRight = 10;
promo.cornerRadius = 9;
promo.counterAxisAlignItems = 'CENTER';
promo.itemSpacing = 10;
promo.fills = [{ type: 'SOLID', color: { r: 0.97, g: 0.98, b: 1 } }];
promo.strokes = [{ type: 'SOLID', color: { r: 0.88, g: 0.9, b: 0.94 } }];
promo.strokeWeight = 1;
const ph = figma.createText();
ph.characters = 'Gift or promo code';
ph.fontSize = 11;
ph.fills = [{ type: 'SOLID', color: { r: 0.5, g: 0.52, b: 0.58 } }];
const apply = figma.createRectangle();
apply.resize(64, 26);
apply.cornerRadius = 7;
apply.fills = [{ type: 'SOLID', color: { r: 0.12, g: 0.14, b: 0.2 } }];
promo.appendChild(ph);
promo.appendChild(apply);
page.appendChild(promo);
const math = createAutoLayout('VERTICAL');
math.resize(408, 92);
math.paddingTop = 10;
math.paddingLeft = 10;
math.paddingRight = 10;
math.paddingBottom = 10;
math.itemSpacing = 8;
math.cornerRadius = 10;
math.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
function rowAmt(label, val, bold) {
  const r = createAutoLayout('HORIZONTAL');
  r.resize(388, 18);
  r.primaryAxisAlignItems = 'SPACE_BETWEEN';
  const l = figma.createText();
  l.characters = label;
  l.fontSize = bold ? 13 : 11;
  l.fills = [{ type: 'SOLID', color: bold ? { r: 0.08, g: 0.09, b: 0.12 } : { r: 0.43, g: 0.45, b: 0.52 } }];
  const p = figma.createText();
  p.characters = val;
  p.fontSize = bold ? 13 : 11;
  p.fills = [{ type: 'SOLID', color: bold ? { r: 0.08, g: 0.09, b: 0.12 } : { r: 0.35, g: 0.37, b: 0.45 } }];
  r.appendChild(l);
  r.appendChild(p);
  return r;
}
math.appendChild(rowAmt('Subtotal', '$276.00', false));
math.appendChild(rowAmt('Estimated tax', '$22.04', false));
math.appendChild(rowAmt('Total', '$298.04', true));
page.appendChild(math);
const pay = createAutoLayout('HORIZONTAL');
pay.resize(408, 46);
pay.cornerRadius = 12;
pay.counterAxisAlignItems = 'CENTER';
pay.primaryAxisAlignItems = 'CENTER';
pay.fills = [{ type: 'SOLID', color: { r: 0.16, g: 0.46, b: 0.98 } }];
pay.effects = [{ type: 'DROP_SHADOW', color: { r: 0.1, g: 0.28, b: 0.8, a: 0.25 }, offset: { x: 0, y: 8 }, radius: 18, blendMode: 'NORMAL', visible: true }];
const payT = figma.createText();
payT.characters = 'Pay $298.04';
payT.fontSize = 15;
payT.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
pay.appendChild(payT);
page.appendChild(pay);
root.appendChild(page);
return { rootId: root.id };
