const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const sq = figma.createRectangle();
sq.resize(100, 100);
sq.x = 140;
sq.y = 130;
sq.fills = [{ type: 'SOLID', color: { r: 0.2, g: 0.5, b: 0.9 } }];
root.appendChild(sq);
const circ = figma.createEllipse();
circ.resize(100, 100);
circ.x = 200;
circ.y = 130;
circ.fills = [{ type: 'SOLID', color: { r: 0.2, g: 0.5, b: 0.9 } }];
root.appendChild(circ);
const u = figma.union([sq, circ], root);
u.fills = [{ type: 'SOLID', color: { r: 0.15, g: 0.45, b: 0.85 } }];
return { rootId: root.id };
