/**
 * Machine-readable capability matrix (design-doc/document-engine.md).
 * Consumed by engine and tests.
 */
const sceneShapeTypes = [
  'FRAME',
  'TEXT',
  'RECTANGLE',
  'ELLIPSE',
  'LINE',
  'POLYGON',
  'STAR',
] as const;

export const ENGINE_MATRIX = {
  createNode: {
    allowedChildPairs: [
      ...sceneShapeTypes.map((child) => ({ parent: 'PAGE' as const, child })),
      ...sceneShapeTypes.map((child) => ({ parent: 'FRAME' as const, child })),
    ],
    allowedRootTypesUnderDocument: ['PAGE' as const],
  },
  patchKeysByType: {
    FRAME: new Set([
      'name',
      'x',
      'y',
      'width',
      'height',
      'fills',
      'backgrounds',
      'strokes',
      'strokeWeight',
      'strokeAlign',
      'strokeCap',
      'strokeJoin',
      'miterLimit',
      'dashPattern',
      'effects',
      'clipsContent',
      'visible',
      'opacity',
      'rotation',
      'blendMode',
    ]),
    TEXT: new Set([
      'name',
      'x',
      'y',
      'width',
      'height',
      'characters',
      'fontSize',
      'fontWeight',
      'fills',
      'styledSegments',
      'effects',
      'visible',
      'opacity',
      'rotation',
      'blendMode',
    ]),
    RECTANGLE: new Set([
      'name',
      'x',
      'y',
      'width',
      'height',
      'fills',
      'strokes',
      'strokeWeight',
      'strokeAlign',
      'strokeCap',
      'strokeJoin',
      'miterLimit',
      'dashPattern',
      'cornerRadius',
      'effects',
      'visible',
      'opacity',
      'rotation',
      'blendMode',
    ]),
    ELLIPSE: new Set([
      'name',
      'x',
      'y',
      'width',
      'height',
      'fills',
      'strokes',
      'strokeWeight',
      'strokeAlign',
      'strokeCap',
      'strokeJoin',
      'miterLimit',
      'dashPattern',
      'arcData',
      'effects',
      'visible',
      'opacity',
      'rotation',
      'blendMode',
    ]),
    LINE: new Set([
      'name',
      'x',
      'y',
      'width',
      'height',
      'strokes',
      'strokeWeight',
      'strokeCap',
      'strokeJoin',
      'dashPattern',
      'effects',
      'visible',
      'opacity',
      'rotation',
      'blendMode',
    ]),
    POLYGON: new Set([
      'name',
      'x',
      'y',
      'width',
      'height',
      'pointCount',
      'fills',
      'strokes',
      'strokeWeight',
      'strokeAlign',
      'strokeCap',
      'strokeJoin',
      'miterLimit',
      'dashPattern',
      'effects',
      'visible',
      'opacity',
      'rotation',
      'blendMode',
    ]),
    STAR: new Set([
      'name',
      'x',
      'y',
      'width',
      'height',
      'pointCount',
      'innerRadius',
      'fills',
      'strokes',
      'strokeWeight',
      'strokeAlign',
      'strokeCap',
      'strokeJoin',
      'miterLimit',
      'dashPattern',
      'effects',
      'visible',
      'opacity',
      'rotation',
      'blendMode',
    ]),
    PAGE: new Set(['name', 'x', 'y', 'width', 'height']),
    DOCUMENT: new Set(['name']),
  },
} as const;
