/**
 * Machine-readable capability matrix (design-doc/document-engine.md).
 * Consumed by engine and tests.
 */
const sceneShapeTypes = [
  'FRAME',
  'TEXT',
  'RECTANGLE',
  'ELLIPSE',
  'LINE',
  'POLYGON',
  'STAR',
  'VECTOR',
  'BOOLEAN_OPERATION',
  'TRANSFORM_GROUP',
  'GROUP',
  'SLICE',
  'SECTION',
  'TABLE',
  'COMPONENT_INSTANCE',
  'INSTANCE',
] as const;

const containerChildTypes = ['FRAME', 'TRANSFORM_GROUP', 'GROUP', 'SECTION'] as const;

const booleanOperandTypes = ['RECTANGLE', 'ELLIPSE', 'POLYGON', 'STAR', 'VECTOR'] as const;

const layoutSelfPatchKeys = [
  'layoutAlign',
  'layoutGrow',
  'minWidth',
  'maxWidth',
  'minHeight',
  'maxHeight',
  'isMask',
  'layoutSizingHorizontal',
  'layoutSizingVertical',
  'layoutPositioning',
  'constraints',
  'gridRowSpan',
  'gridColumnSpan',
  'gridRowAnchorIndex',
  'gridColumnAnchorIndex',
  'gridChildHorizontalAlign',
  'gridChildVerticalAlign',
] as const;

const shapePatchKeys = [
  'name',
  'x',
  'y',
  'width',
  'height',
  'visible',
  'opacity',
  'rotation',
  'blendMode',
  ...layoutSelfPatchKeys,
] as const;

export const ENGINE_MATRIX = {
  createNode: {
    allowedChildPairs: [
      { parent: 'DOCUMENT' as const, child: 'PAGE' as const },
      ...sceneShapeTypes.map((child) => ({ parent: 'PAGE' as const, child })),
      ...sceneShapeTypes.map((child) => ({ parent: 'FRAME' as const, child })),
      ...sceneShapeTypes.map((child) => ({ parent: 'TRANSFORM_GROUP' as const, child })),
      ...sceneShapeTypes.map((child) => ({ parent: 'GROUP' as const, child })),
      ...sceneShapeTypes.map((child) => ({ parent: 'SECTION' as const, child })),
      // Phase 9 — component wrappers live on PAGE (component page convention).
      { parent: 'PAGE' as const, child: 'COMPONENT' as const },
      { parent: 'PAGE' as const, child: 'COMPONENT_SET' as const },
      ...booleanOperandTypes.map((child) => ({ parent: 'BOOLEAN_OPERATION' as const, child })),
    ],
    allowedRootTypesUnderDocument: ['PAGE' as const],
  },
  patchKeysByType: {
    FRAME: new Set([
      ...shapePatchKeys,
      'fills',
      'backgrounds',
      'strokes',
      'strokeWeight',
      'strokeAlign',
      'strokeCap',
      'strokeJoin',
      'miterLimit',
      'dashPattern',
      'cornerRadius',
      'topLeftRadius',
      'topRightRadius',
      'bottomRightRadius',
      'bottomLeftRadius',
      'cornerSmoothing',
      'individualStrokeWeights',
      'strokeTopWeight',
      'strokeRightWeight',
      'strokeBottomWeight',
      'strokeLeftWeight',
      'effects',
      'clipsContent',
      'itemReverseZIndex',
      'strokesIncludedInLayout',
      'fillStyleId',
      'strokeStyleId',
      'effectStyleId',
      'gridStyleId',
      'explicitVariableModes',
      'layoutMode',
      'gridRowCount',
      'gridColumnCount',
      'gridRowGap',
      'gridColumnGap',
      'gridRowSizes',
      'gridColumnSizes',
      'paddingLeft',
      'paddingRight',
      'paddingTop',
      'paddingBottom',
      'itemSpacing',
      'layoutWrap',
      'counterAxisSpacing',
      'counterAxisAlignContent',
      'primaryAxisAlignItems',
      'counterAxisAlignItems',
      'layoutGrids',
      'primaryAxisSizingMode',
      'counterAxisSizingMode',
      'boundVariables',
    ]),
    TEXT: new Set([
      ...shapePatchKeys,
      'characters',
      'fontSize',
      'fontWeight',
      'fontName',
      'fills',
      'styledSegments',
      'effects',
      'textStyleId',
      'textOnPath',
      'textAutoResize',
      'textTruncation',
      'maxLines',
      'textAlignHorizontal',
      'textAlignVertical',
      'lineHeight',
      'letterSpacing',
      'leadingTrim',
      'paragraphIndent',
      'paragraphSpacing',
      'listSpacing',
      'hangingPunctuation',
      'hangingList',
      'listOptions',
      'strokes',
      'strokeWeight',
      'strokeAlign',
      'strokeCap',
      'strokeJoin',
      'miterLimit',
      'dashPattern',
      'fillStyleId',
      'strokeStyleId',
      'effectStyleId',
      'explicitVariableModes',
      'boundVariables',
    ]),
    RECTANGLE: new Set([
      ...shapePatchKeys,
      'fills',
      'strokes',
      'strokeWeight',
      'strokeAlign',
      'strokeCap',
      'strokeJoin',
      'miterLimit',
      'dashPattern',
      'cornerRadius',
      'topLeftRadius',
      'topRightRadius',
      'bottomRightRadius',
      'bottomLeftRadius',
      'cornerSmoothing',
      'individualStrokeWeights',
      'strokeTopWeight',
      'strokeRightWeight',
      'strokeBottomWeight',
      'strokeLeftWeight',
      'effects',
      'fillStyleId',
      'effectStyleId',
    ]),
    ELLIPSE: new Set([
      ...shapePatchKeys,
      'fills',
      'strokes',
      'strokeWeight',
      'strokeAlign',
      'strokeCap',
      'strokeJoin',
      'miterLimit',
      'dashPattern',
      'arcData',
      'effects',
    ]),
    LINE: new Set([
      ...shapePatchKeys,
      'strokes',
      'strokeWeight',
      'strokeCap',
      'strokeJoin',
      'dashPattern',
      'effects',
    ]),
    POLYGON: new Set([
      ...shapePatchKeys,
      'pointCount',
      'fills',
      'strokes',
      'strokeWeight',
      'strokeAlign',
      'strokeCap',
      'strokeJoin',
      'miterLimit',
      'dashPattern',
      'effects',
    ]),
    STAR: new Set([
      ...shapePatchKeys,
      'pointCount',
      'innerRadius',
      'fills',
      'strokes',
      'strokeWeight',
      'strokeAlign',
      'strokeCap',
      'strokeJoin',
      'miterLimit',
      'dashPattern',
      'effects',
    ]),
    VECTOR: new Set([
      ...shapePatchKeys,
      'vectorPaths',
      'fills',
      'strokes',
      'strokeWeight',
      'strokeAlign',
      'strokeCap',
      'strokeJoin',
      'miterLimit',
      'dashPattern',
      'effects',
    ]),
    BOOLEAN_OPERATION: new Set([
      ...shapePatchKeys,
      'booleanOperation',
      'fills',
      'effects',
    ]),
    TRANSFORM_GROUP: new Set([...shapePatchKeys, 'transformModifiers']),
    GROUP: new Set([...shapePatchKeys]),
    SLICE: new Set([...shapePatchKeys]),
    SECTION: new Set([...shapePatchKeys, 'fills']),
    TABLE: new Set([
      ...shapePatchKeys,
      'columnCount',
      'rowCount',
      'columnWidths',
      'rowHeights',
      'cells',
    ]),
    COMPONENT_INSTANCE: new Set([...shapePatchKeys, 'mainComponentId', 'overrides']),
    COMPONENT: new Set([...shapePatchKeys, 'rootFrameId', 'componentKey', 'componentPropertyDefinitions']),
    COMPONENT_SET: new Set([
      ...shapePatchKeys,
      'componentKey',
      'componentIds',
      'variantPropertyKey',
      'variantOptions',
      'nodeIdMapByComponentId',
      'baseComponentId',
    ]),
    INSTANCE: new Set([...shapePatchKeys, 'mainComponentId', 'componentProperties', 'overrides']),
    PAGE: new Set(['name', 'x', 'y', 'width', 'height', 'backgrounds', 'isPageDivider']),
    DOCUMENT: new Set(['name']),
  },
} as const;

export { containerChildTypes, sceneShapeTypes };
