/**
 * Machine-readable capability matrix (design-doc/document-engine.md).
 * Consumed by engine and tests.
 */
const sceneShapeTypes = [
  'FRAME',
  'TEXT',
  'RECTANGLE',
  'ELLIPSE',
  'LINE',
  'POLYGON',
  'STAR',
  'VECTOR',
  'BOOLEAN_OPERATION',
  'TRANSFORM_GROUP',
  'GROUP',
  'SLICE',
  'SECTION',
  'TABLE',
  'COMPONENT_INSTANCE',
  'INSTANCE',
] as const;

const containerChildTypes = ['FRAME', 'TRANSFORM_GROUP', 'GROUP', 'SECTION'] as const;

const booleanOperandTypes = ['RECTANGLE', 'ELLIPSE', 'POLYGON', 'STAR', 'VECTOR'] as const;

const layoutSelfPatchKeys = [
  'layoutAlign',
  'layoutGrow',
  'minWidth',
  'maxWidth',
  'minHeight',
  'maxHeight',
  'isMask',
  'layoutSizingHorizontal',
  'layoutSizingVertical',
  'layoutPositioning',
  'constraints',
  'gridRowSpan',
  'gridColumnSpan',
  'gridRowAnchorIndex',
  'gridColumnAnchorIndex',
  'gridChildHorizontalAlign',
  'gridChildVerticalAlign',
] as const;

const shapePatchKeys = [
  'name',
  'x',
  'y',
  'width',
  'height',
  'visible',
  'opacity',
  'rotation',
  'blendMode',
  ...layoutSelfPatchKeys,
] as const;

/** Stub scene fields merged into shape-backed patch sets. */
const shapePatchKeysWithLocked = [...shapePatchKeys, 'locked'] as const;

const devStatusPatchKeys = ['devStatus'] as const;

const sectionStrokePatchKeys = [
  'strokes',
  'strokeWeight',
  'strokeAlign',
  'strokeCap',
  'strokeJoin',
  'miterLimit',
  'dashPattern',
] as const;

/** Auto-layout frame fields (Figma: FrameNode + InstanceNode). */
const autoLayoutPatchKeys = [
  'layoutMode',
  'gridRowCount',
  'gridColumnCount',
  'gridRowGap',
  'gridColumnGap',
  'gridRowSizes',
  'gridColumnSizes',
  'paddingLeft',
  'paddingRight',
  'paddingTop',
  'paddingBottom',
  'itemSpacing',
  'layoutWrap',
  'counterAxisSpacing',
  'counterAxisAlignContent',
  'primaryAxisAlignItems',
  'counterAxisAlignItems',
  'layoutGrids',
  'primaryAxisSizingMode',
  'counterAxisSizingMode',
  'itemReverseZIndex',
  'strokesIncludedInLayout',
] as const;

export const ENGINE_MATRIX = {
  createNode: {
    allowedChildPairs: [
      { parent: 'DOCUMENT' as const, child: 'PAGE' as const },
      ...sceneShapeTypes.map((child) => ({ parent: 'PAGE' as const, child })),
      ...sceneShapeTypes.map((child) => ({ parent: 'FRAME' as const, child })),
      ...sceneShapeTypes.map((child) => ({ parent: 'TRANSFORM_GROUP' as const, child })),
      ...sceneShapeTypes.map((child) => ({ parent: 'GROUP' as const, child })),
      ...sceneShapeTypes.map((child) => ({ parent: 'SECTION' as const, child })),
      // Phase 9 — component wrappers live on PAGE (component page convention).
      { parent: 'PAGE' as const, child: 'COMPONENT' as const },
      { parent: 'PAGE' as const, child: 'COMPONENT_SET' as const },
      ...booleanOperandTypes.map((child) => ({ parent: 'BOOLEAN_OPERATION' as const, child })),
    ],
    allowedRootTypesUnderDocument: ['PAGE' as const],
  },
  patchKeysByType: {
    FRAME: new Set([
      ...shapePatchKeysWithLocked,
      ...devStatusPatchKeys,
      'fills',
      'backgrounds',
      'strokes',
      'strokeWeight',
      'strokeAlign',
      'strokeCap',
      'strokeJoin',
      'miterLimit',
      'dashPattern',
      'cornerRadius',
      'topLeftRadius',
      'topRightRadius',
      'bottomRightRadius',
      'bottomLeftRadius',
      'cornerSmoothing',
      'individualStrokeWeights',
      'strokeTopWeight',
      'strokeRightWeight',
      'strokeBottomWeight',
      'strokeLeftWeight',
      'effects',
      'clipsContent',
      'itemReverseZIndex',
      'strokesIncludedInLayout',
      'fillStyleId',
      'strokeStyleId',
      'effectStyleId',
      'gridStyleId',
      'explicitVariableModes',
      ...autoLayoutPatchKeys,
      'boundVariables',
    ]),
    TEXT: new Set([
      ...shapePatchKeysWithLocked,
      'characters',
      'fontSize',
      'fontWeight',
      'fontName',
      'fills',
      'styledSegments',
      'effects',
      'textStyleId',
      'textOnPath',
      'textAutoResize',
      'textTruncation',
      'maxLines',
      'textAlignHorizontal',
      'textAlignVertical',
      'lineHeight',
      'letterSpacing',
      'leadingTrim',
      'paragraphIndent',
      'paragraphSpacing',
      'listSpacing',
      'hangingPunctuation',
      'hangingList',
      'listOptions',
      'strokes',
      'strokeWeight',
      'strokeAlign',
      'strokeCap',
      'strokeJoin',
      'miterLimit',
      'dashPattern',
      'fillStyleId',
      'strokeStyleId',
      'effectStyleId',
      'explicitVariableModes',
      'boundVariables',
    ]),
    RECTANGLE: new Set([
      ...shapePatchKeysWithLocked,
      'fills',
      'strokes',
      'strokeWeight',
      'strokeAlign',
      'strokeCap',
      'strokeJoin',
      'miterLimit',
      'dashPattern',
      'cornerRadius',
      'topLeftRadius',
      'topRightRadius',
      'bottomRightRadius',
      'bottomLeftRadius',
      'cornerSmoothing',
      'individualStrokeWeights',
      'strokeTopWeight',
      'strokeRightWeight',
      'strokeBottomWeight',
      'strokeLeftWeight',
      'effects',
      'fillStyleId',
      'strokeStyleId',
      'effectStyleId',
    ]),
    ELLIPSE: new Set([
      ...shapePatchKeysWithLocked,
      'fills',
      'strokes',
      'strokeWeight',
      'strokeAlign',
      'strokeCap',
      'strokeJoin',
      'miterLimit',
      'dashPattern',
      'arcData',
      'effects',
      'fillStyleId',
      'strokeStyleId',
      'effectStyleId',
    ]),
    LINE: new Set([
      ...shapePatchKeysWithLocked,
      'strokes',
      'strokeWeight',
      'strokeCap',
      'strokeJoin',
      'dashPattern',
      'effects',
      'fillStyleId',
      'strokeStyleId',
      'effectStyleId',
    ]),
    POLYGON: new Set([
      ...shapePatchKeysWithLocked,
      'pointCount',
      'fills',
      'strokes',
      'strokeWeight',
      'strokeAlign',
      'strokeCap',
      'strokeJoin',
      'miterLimit',
      'dashPattern',
      'effects',
      'fillStyleId',
      'strokeStyleId',
      'effectStyleId',
    ]),
    STAR: new Set([
      ...shapePatchKeysWithLocked,
      'pointCount',
      'innerRadius',
      'fills',
      'strokes',
      'strokeWeight',
      'strokeAlign',
      'strokeCap',
      'strokeJoin',
      'miterLimit',
      'dashPattern',
      'effects',
      'fillStyleId',
      'strokeStyleId',
      'effectStyleId',
    ]),
    VECTOR: new Set([
      ...shapePatchKeysWithLocked,
      'vectorPaths',
      'fills',
      'strokes',
      'strokeWeight',
      'strokeAlign',
      'strokeCap',
      'strokeJoin',
      'miterLimit',
      'dashPattern',
      'effects',
      'fillStyleId',
      'strokeStyleId',
      'effectStyleId',
    ]),
    BOOLEAN_OPERATION: new Set([
      ...shapePatchKeysWithLocked,
      'booleanOperation',
      'fills',
      'effects',
      'fillStyleId',
      'strokeStyleId',
      'effectStyleId',
    ]),
    TRANSFORM_GROUP: new Set([...shapePatchKeysWithLocked, 'transformModifiers']),
    GROUP: new Set([...shapePatchKeysWithLocked]),
    SLICE: new Set([...shapePatchKeysWithLocked]),
    SECTION: new Set([
      ...shapePatchKeysWithLocked,
      ...devStatusPatchKeys,
      'fills',
      ...sectionStrokePatchKeys,
      'sectionContentsHidden',
    ]),
    TABLE: new Set([
      ...shapePatchKeysWithLocked,
      'columnCount',
      'rowCount',
      'columnWidths',
      'rowHeights',
      'cells',
    ]),
    COMPONENT_INSTANCE: new Set([...shapePatchKeysWithLocked, 'mainComponentId', 'overrides']),
    COMPONENT: new Set([
      ...shapePatchKeysWithLocked,
      ...devStatusPatchKeys,
      'rootFrameId',
      'componentKey',
      'componentPropertyDefinitions',
    ]),
    COMPONENT_SET: new Set([
      ...shapePatchKeysWithLocked,
      ...devStatusPatchKeys,
      'componentKey',
      'componentIds',
      'componentPropertyDefinitions',
      'variantPropertyKey',
      'variantOptions',
      'nodeIdMapByComponentId',
      'baseComponentId',
    ]),
    INSTANCE: new Set([
      ...shapePatchKeysWithLocked,
      ...devStatusPatchKeys,
      'fills',
      'backgrounds',
      'strokes',
      'strokeWeight',
      'strokeAlign',
      'strokeCap',
      'strokeJoin',
      'miterLimit',
      'dashPattern',
      'cornerRadius',
      'topLeftRadius',
      'topRightRadius',
      'bottomRightRadius',
      'bottomLeftRadius',
      'cornerSmoothing',
      'individualStrokeWeights',
      'effects',
      'clipsContent',
      'fillStyleId',
      'strokeStyleId',
      'effectStyleId',
      'boundVariables',
      'mainComponentId',
      'componentProperties',
      'overrides',
      'scaleFactor',
      ...autoLayoutPatchKeys,
    ]),
    PAGE: new Set(['name', 'x', 'y', 'width', 'height', 'backgrounds', 'isPageDivider']),
    DOCUMENT: new Set(['name']),
  },
} as const;

export { containerChildTypes, sceneShapeTypes };
