const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const bottom = figma.createRectangle();
bottom.resize(200, 140);
bottom.x = 140;
bottom.y = 110;
bottom.fills = [{ type: 'SOLID', color: { r: 0.2, g: 0.75, b: 0.35 } }];
root.appendChild(bottom);
const hidden = figma.createRectangle();
hidden.resize(200, 140);
hidden.x = 160;
hidden.y = 120;
hidden.fills = [{ type: 'SOLID', color: { r: 0.9, g: 0.2, b: 0.2 } }];
hidden.visible = false;
root.appendChild(hidden);
const top = figma.createRectangle();
top.resize(120, 80);
top.x = 200;
top.y = 140;
top.fills = [{ type: 'SOLID', color: { r: 0.2, g: 0.4, b: 0.9 } }];
root.appendChild(top);
return { rootId: root.id };
