const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const outer = figma.createFrame();
outer.resize(280, 160);
outer.x = 100;
outer.y = 100;
outer.clipsContent = true;
outer.fills = [{ type: 'SOLID', color: { r: 0.9, g: 0.92, b: 0.96 } }];
const inner = figma.createFrame();
inner.resize(200, 120);
inner.x = 60;
inner.y = 20;
inner.clipsContent = false;
inner.fills = [{ type: 'SOLID', color: { r: 0.85, g: 0.88, b: 0.92 } }];
const child = figma.createRectangle();
child.resize(120, 80);
child.x = 80;
child.y = 60;
child.fills = [{ type: 'SOLID', color: { r: 0.9, g: 0.35, b: 0.15 } }];
inner.appendChild(child);
outer.appendChild(inner);
root.appendChild(outer);
return { rootId: root.id };
