const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const row = figma.createAutoLayout();
row.resize(360, 48);
row.x = 60;
row.y = 156;
row.itemSpacing = 8;
const fill = figma.createRectangle();
fill.name = 'Fill';
fill.resize(80, 40);
fill.layoutSizingHorizontal = 'FILL';
fill.fills = [{ type: 'SOLID', color: { r: 0.2, g: 0.75, b: 0.35 } }];
const hug = figma.createRectangle();
hug.name = 'Hug';
hug.resize(50, 40);
hug.layoutSizingHorizontal = 'HUG';
hug.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.55, b: 0.1 } }];
row.appendChild(fill);
row.appendChild(hug);
root.appendChild(row);
return { rootId: root.id };
