const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const col = figma.variables.createVariableCollection('Brand');
const modeId = col.modes[0].id;
const brand = figma.variables.createVariable('primary', col, 'COLOR');
figma.variables.setValueForMode(brand.id, modeId, { type: 'COLOR', color: { r: 0.9, g: 0.15, b: 0.2 } });
const rect = figma.createRectangle();
rect.resize(200, 100);
rect.x = 140;
rect.y = 130;
root.appendChild(rect);
rect.setBoundVariable('fills', brand);
return { rootId: root.id };
