await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
function createAutoLayout(direction) {
  if (typeof figma.createAutoLayout === 'function') {
    return figma.createAutoLayout(direction);
  }
  const frame = figma.createFrame();
  frame.layoutMode = direction === 'VERTICAL' ? 'VERTICAL' : 'HORIZONTAL';
  return frame;
}
const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const flow = createAutoLayout('VERTICAL');
flow.resize(400, 318);
flow.x = 40;
flow.y = 20;
flow.itemSpacing = 18;
flow.primaryAxisAlignItems = 'CENTER';
flow.counterAxisAlignItems = 'CENTER';
const stepper = createAutoLayout('HORIZONTAL');
stepper.itemSpacing = 16;
stepper.counterAxisAlignItems = 'CENTER';
function step(n, label, active, done) {
  const col = createAutoLayout('VERTICAL');
  col.itemSpacing = 6;
  col.primaryAxisAlignItems = 'CENTER';
  const disc = createAutoLayout('VERTICAL');
  disc.resize(36, 36);
  disc.cornerRadius = 18;
  disc.primaryAxisAlignItems = 'CENTER';
  disc.counterAxisAlignItems = 'CENTER';
  disc.fills = [{ type: 'SOLID', color: active ? { r: 0.14, g: 0.42, b: 0.98 } : done ? { r: 0.22, g: 0.72, b: 0.48 } : { r: 0.9, g: 0.91, b: 0.94 } }];
  const txt = figma.createText();
  txt.characters = String(n);
  txt.fontSize = 14;
  txt.fills = [{ type: 'SOLID', color: active || done ? { r: 1, g: 1, b: 1 } : { r: 0.45, g: 0.46, b: 0.52 } }];
  disc.appendChild(txt);
  const lb = figma.createText();
  lb.characters = label;
  lb.fontSize = 9;
  lb.fills = [{ type: 'SOLID', color: { r: 0.4, g: 0.42, b: 0.5 } }];
  col.appendChild(disc);
  col.appendChild(lb);
  return col;
}
stepper.appendChild(step(1, 'Workspace', false, true));
stepper.appendChild(step(2, 'Invite', true, false));
stepper.appendChild(step(3, 'Ship', false, false));
flow.appendChild(stepper);
const illo = figma.createFrame();
illo.resize(360, 140);
illo.cornerRadius = 18;
illo.fills = [{ type: 'GRADIENT_LINEAR', gradientStops: [{ position: 0, color: { r: 0.93, g: 0.95, b: 1, a: 1 } }, { position: 1, color: { r: 0.88, g: 0.9, b: 1, a: 1 } }], gradientTransform: [[1, 0, 0], [0, 1, 0]] }];
illo.strokes = [{ type: 'SOLID', color: { r: 0.86, g: 0.88, b: 0.93 } }];
illo.strokeWeight = 1;
const deco1 = figma.createRectangle();
deco1.resize(120, 12);
deco1.x = 40;
deco1.y = 40;
deco1.cornerRadius = 6;
deco1.fills = [{ type: 'SOLID', color: { r: 0.78, g: 0.84, b: 0.98 } }];
const deco2 = figma.createRectangle();
deco2.resize(180, 12);
deco2.x = 40;
deco2.y = 62;
deco2.cornerRadius = 6;
deco2.fills = [{ type: 'SOLID', color: { r: 0.86, g: 0.9, b: 0.99 } }];
const deco3 = figma.createRectangle();
deco3.resize(90, 90);
deco3.x = 230;
deco3.y = 34;
deco3.cornerRadius = 22;
deco3.fills = [{ type: 'SOLID', color: { r: 0.72, g: 0.82, b: 1, a: 0.55 } }];
illo.appendChild(deco1);
illo.appendChild(deco2);
illo.appendChild(deco3);
flow.appendChild(illo);
const title = figma.createText();
title.characters = 'Bring your collaborators';
title.fontSize = 20;
title.fills = [{ type: 'SOLID', color: { r: 0.07, g: 0.08, b: 0.12 } }];
flow.appendChild(title);
const bullets = createAutoLayout('VERTICAL');
bullets.itemSpacing = 8;
for (const line of ['Guests preview without seats', 'Granular library permissions', 'Activity log in Scale tier']) {
  const row = createAutoLayout('HORIZONTAL');
  row.itemSpacing = 8;
  row.counterAxisAlignItems = 'CENTER';
  const dot = figma.createRectangle();
  dot.resize(6, 6);
  dot.cornerRadius = 3;
  dot.fills = [{ type: 'SOLID', color: { r: 0.2, g: 0.45, b: 0.98 } }];
  const t = figma.createText();
  t.characters = line;
  t.fontSize = 11;
  t.fills = [{ type: 'SOLID', color: { r: 0.3, g: 0.32, b: 0.38 } }];
  row.appendChild(dot);
  row.appendChild(t);
  bullets.appendChild(row);
}
flow.appendChild(bullets);
const ctas = createAutoLayout('HORIZONTAL');
ctas.itemSpacing = 12;
const prim = figma.createRectangle();
prim.resize(140, 40);
prim.cornerRadius = 12;
prim.fills = [{ type: 'SOLID', color: { r: 0.14, g: 0.42, b: 0.98 } }];
const sec = figma.createRectangle();
sec.resize(120, 40);
sec.cornerRadius = 12;
sec.fills = [{ type: 'SOLID', color: { r: 0.96, g: 0.97, b: 1 } }];
sec.strokes = [{ type: 'SOLID', color: { r: 0.85, g: 0.87, b: 0.92 } }];
sec.strokeWeight = 1;
ctas.appendChild(prim);
ctas.appendChild(sec);
flow.appendChild(ctas);
root.appendChild(flow);
return { rootId: root.id };
