await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const brand = figma.variables.createVariableCollection('UI');
const modeId = brand.modes[0].id;
const primary = figma.variables.createVariable('primary', brand, 'COLOR');
figma.variables.setValueForMode(primary.id, modeId, { type: 'COLOR', color: { r: 0.15, g: 0.45, b: 0.95 } });
const header = figma.createAutoLayout();
header.resize(440, 48);
header.x = 20;
header.y = 12;
header.itemSpacing = 16;
header.counterAxisAlignItems = 'CENTER';
header.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
const logo = figma.createRectangle();
logo.resize(28, 28);
logo.fills = [{ type: 'SOLID', color: { r: 0.15, g: 0.45, b: 0.95 } }];
header.appendChild(logo);
const nav = figma.createText();
nav.characters = 'Product  Pricing';
nav.fontSize = 13;
header.appendChild(nav);
root.appendChild(header);
const hero = figma.createRectangle();
hero.resize(440, 120);
hero.x = 20;
hero.y = 68;
hero.fills = [{ type: 'GRADIENT_LINEAR', gradientStops: [{ position: 0, color: { r: 0.1, g: 0.35, b: 0.85, a: 1 } }, { position: 1, color: { r: 0.45, g: 0.2, b: 0.75, a: 1 } }], gradientTransform: [[1,0,0],[0,1,0]] }];
root.appendChild(hero);
const avatar = figma.createEllipse();
avatar.resize(64, 64);
avatar.x = 48;
avatar.y = 96;
avatar.fills = [{ type: 'SOLID', color: { r: 0.9, g: 0.75, b: 0.5 } }];
root.appendChild(avatar);
const avatarMask = figma.createEllipse();
avatarMask.resize(64, 64);
avatarMask.x = 48;
avatarMask.y = 96;
avatarMask.isMask = true;
avatarMask.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
root.appendChild(avatarMask);
const badge = figma.createEllipse();
badge.resize(20, 20);
badge.x = 400;
badge.y = 20;
badge.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.2, b: 0.2 } }];
root.appendChild(badge);
for (let i = 0; i < 2; i++) {
  const card = figma.createRectangle();
  card.resize(160, 90);
  card.x = 40 + i * 120;
  card.y = 200 + i * 12;
  card.cornerRadius = 10;
  card.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
  card.effects = [{ type: 'DROP_SHADOW', color: { r: 0, g: 0, b: 0, a: 0.15 }, offset: { x: 0, y: 4 }, radius: 12, visible: true }];
  root.appendChild(card);
}
const modal = figma.createFrame();
modal.resize(280, 100);
modal.x = 100;
modal.y = 210;
modal.cornerRadius = 12;
modal.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1, a: 0.35 } }];
modal.effects = [{ type: 'BACKDROP_BLUR', radius: 12, visible: true }];
root.appendChild(modal);
return { rootId: root.id };
