const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const bg = figma.createRectangle();
bg.resize(320, 200);
bg.x = 80;
bg.y = 80;
bg.fills = [{ type: 'GRADIENT_LINEAR', gradientStops: [{ position: 0, color: { r: 0.1, g: 0.35, b: 0.85, a: 1 } }, { position: 1, color: { r: 0.5, g: 0.2, b: 0.75, a: 1 } }], gradientTransform: [[1,0,0],[0,1,0]] }];
root.appendChild(bg);
const vec = figma.createVector();
vec.resize(80, 70);
vec.x = 200;
vec.y = 145;
vec.vectorPaths = [{ windingRule: 'NONZERO', data: 'M 40 8 L 72 62 L 8 62 Z' }];
vec.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
root.appendChild(vec);
return { rootId: root.id };
