const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const parent = figma.createFrame();
parent.resize(240, 180);
parent.x = 120;
parent.y = 90;
parent.clipsContent = true;
parent.fills = [{ type: 'SOLID', color: { r: 0.92, g: 0.93, b: 0.96 } }];
const child = figma.createRectangle();
child.resize(200, 80);
child.x = 40;
child.y = 60;
child.rotation = 25;
child.fills = [{ type: 'SOLID', color: { r: 0.9, g: 0.4, b: 0.1 } }];
parent.appendChild(child);
root.appendChild(parent);
return { rootId: root.id };
