await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const table = figma.createTable(3, 3);
table.x = 90;
table.y = 60;
table.resize(300, 200);
root.appendChild(table);
return { rootId: root.id };
