await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
function createAutoLayout(direction) {
  if (typeof figma.createAutoLayout === 'function') {
    return figma.createAutoLayout(direction);
  }
  const frame = figma.createFrame();
  frame.layoutMode = direction === 'VERTICAL' ? 'VERTICAL' : 'HORIZONTAL';
  return frame;
}
const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const board = figma.variables.createVariableCollection('Kanban');
const modeId = board.modes[0].modeId;
const sprintTitle = figma.variables.createVariable('sprintTitle', board, 'STRING');
sprintTitle.setValueForMode(modeId, 'Sprint 24 · Ship milestones');
const tintTodo = figma.variables.createVariable('colTodo', board, 'COLOR');
tintTodo.setValueForMode(modeId, { r: 0.93, g: 0.95, b: 1 });
const tintDoing = figma.variables.createVariable('colDoing', board, 'COLOR');
tintDoing.setValueForMode(modeId, { r: 0.97, g: 0.93, b: 1 });
const tintDone = figma.variables.createVariable('colDone', board, 'COLOR');
tintDone.setValueForMode(modeId, { r: 0.92, g: 1, b: 0.95 });
const statusPill = figma.variables.createVariable('statusPill', board, 'COLOR');
statusPill.setValueForMode(modeId, { r: 0.14, g: 0.68, b: 0.42 });
const barBase = figma.variables.createVariable('barBase', board, 'COLOR');
barBase.setValueForMode(modeId, { r: 0.1, g: 0.45, b: 0.95 });
const barResolved = figma.variables.createVariable('barViaAlias', board, 'COLOR');
barResolved.setValueForMode(modeId, figma.variables.createVariableAlias(barBase));
function makeCard(i) {
  const card = createAutoLayout('VERTICAL');
  card.itemSpacing = 6;
  card.paddingTop = 8;
  card.paddingLeft = 8;
  card.paddingRight = 8;
  card.paddingBottom = 8;
  card.cornerRadius = 8;
  card.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
  card.strokes = [{ type: 'SOLID', color: { r: 0.86, g: 0.89, b: 0.94 } }];
  card.strokeWeight = 1;
  card.effects = [{ type: 'DROP_SHADOW', color: { r: 0, g: 0, b: 0, a: 0.1 }, offset: { x: 0, y: 2 }, radius: 8, blendMode: 'NORMAL', visible: true }];
  const line1 = figma.createText();
  line1.characters = i % 2 === 0 ? 'Spec tokens' : 'E2E harness';
  line1.fontSize = 12;
  const bar = figma.createRectangle();
  bar.resize(108, 5);
  bar.cornerRadius = 3;
  bar.fills = [figma.variables.setBoundVariableForPaint({ type: 'SOLID', color: { r: 0, g: 0, b: 0 } }, 'color', barResolved)];
  const tags = createAutoLayout('HORIZONTAL');
  tags.itemSpacing = 4;
  const a = figma.createRectangle();
  a.resize(40, 12);
  a.cornerRadius = 4;
  a.fills = [{ type: 'SOLID', color: { r: 0.94, g: 0.95, b: 0.98 } }];
  const b = figma.createRectangle();
  b.resize(32, 12);
  b.cornerRadius = 4;
  b.fills = [{ type: 'SOLID', color: { r: 0.96, g: 0.93, b: 1 } }];
  tags.appendChild(a);
  tags.appendChild(b);
  card.appendChild(line1);
  card.appendChild(bar);
  card.appendChild(tags);
  return card;
}
function makeColumn(tintVar, heading, nCards) {
  const shell = createAutoLayout('VERTICAL');
  shell.itemSpacing = 8;
  shell.paddingTop = 10;
  shell.paddingLeft = 8;
  shell.paddingRight = 8;
  shell.paddingBottom = 10;
  shell.cornerRadius = 10;
  shell.fills = [figma.variables.setBoundVariableForPaint({ type: 'SOLID', color: { r: 0.96, g: 0.96, b: 0.98 } }, 'color', tintVar)];
  const h = figma.createText();
  h.characters = heading;
  h.fontSize = 11;
  shell.appendChild(h);
  for (let i = 0; i < nCards; i++) shell.appendChild(makeCard(i + (heading === 'Doing' ? 2 : 0)));
  shell.resize(138, 252);
  return shell;
}
const header = createAutoLayout('HORIZONTAL');
header.resize(440, 40);
header.x = 20;
header.y = 14;
header.itemSpacing = 14;
header.counterAxisAlignItems = 'CENTER';
header.primaryAxisAlignItems = 'SPACE_BETWEEN';
const boardTitle = figma.createText();
boardTitle.fontSize = 17;
boardTitle.setBoundVariable('characters', sprintTitle);
const pill = createAutoLayout('HORIZONTAL');
pill.paddingLeft = 12;
pill.paddingRight = 12;
pill.paddingTop = 5;
pill.paddingBottom = 5;
pill.cornerRadius = 16;
pill.counterAxisAlignItems = 'CENTER';
pill.fills = [figma.variables.setBoundVariableForPaint({ type: 'SOLID', color: { r: 0, g: 0, b: 0 } }, 'color', statusPill)];
const pillLabel = figma.createText();
pillLabel.characters = 'On track';
pillLabel.fontSize = 11;
pillLabel.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
pill.appendChild(pillLabel);
header.appendChild(boardTitle);
header.appendChild(pill);
root.appendChild(header);
const lanes = createAutoLayout('HORIZONTAL');
lanes.resize(440, 268);
lanes.x = 20;
lanes.y = 62;
lanes.itemSpacing = 10;
lanes.counterAxisAlignItems = 'MAX';
lanes.appendChild(makeColumn(tintTodo, 'Backlog', 3));
lanes.appendChild(makeColumn(tintDoing, 'Doing', 2));
lanes.appendChild(makeColumn(tintDone, 'Done', 2));
root.appendChild(lanes);
return { rootId: root.id };
