await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
function createAutoLayout(direction) {
  if (typeof figma.createAutoLayout === 'function') {
    return figma.createAutoLayout(direction);
  }
  const frame = figma.createFrame();
  frame.layoutMode = direction === 'VERTICAL' ? 'VERTICAL' : 'HORIZONTAL';
  return frame;
}
const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const canvas = figma.createFrame();
canvas.resize(440, 292);
canvas.x = 20;
canvas.y = 34;
canvas.fills = [];
const heading = figma.createText();
heading.characters = 'FY26 delivery preview';
heading.fontSize = 16;
heading.x = 20;
heading.y = 0;
heading.fills = [{ type: 'SOLID', color: { r: 0.08, g: 0.1, b: 0.15 } }];
canvas.appendChild(heading);
const rail = figma.createRectangle();
rail.resize(400, 4);
rail.x = 20;
rail.y = 46;
rail.cornerRadius = 2;
rail.fills = [{ type: 'SOLID', color: { r: 0.86, g: 0.88, b: 0.94 } }];
canvas.appendChild(rail);
function milestone(x, label, caption, cardTitle, owner, tint) {
  const node = figma.createEllipse();
  node.resize(18, 18);
  node.x = x;
  node.y = 39;
  node.fills = [{ type: 'SOLID', color: { r: 0.14, g: 0.42, b: 0.98 } }];
  node.strokes = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
  node.strokeWeight = 3;
  canvas.appendChild(node);
  const lb = figma.createText();
  lb.characters = label;
  lb.fontSize = 10;
  lb.fills = [{ type: 'SOLID', color: { r: 0.32, g: 0.34, b: 0.42 } }];
  lb.x = x - 18;
  lb.y = 12;
  canvas.appendChild(lb);
  const cap = figma.createText();
  cap.characters = caption;
  cap.fontSize = 11;
  cap.fills = [{ type: 'SOLID', color: { r: 0.12, g: 0.14, b: 0.2 } }];
  cap.x = x - 28;
  cap.y = 70;
  canvas.appendChild(cap);
  const card = figma.createFrame();
  card.resize(128, 88);
  card.x = x - 54;
  card.y = 96;
  card.cornerRadius = 12;
  card.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
  card.effects = [{ type: 'DROP_SHADOW', color: { r: 0, g: 0, b: 0, a: 0.1 }, offset: { x: 0, y: 6 }, radius: 14, blendMode: 'NORMAL', visible: true }];
  card.strokes = [{ type: 'SOLID', color: { r: 0.9, g: 0.91, b: 0.95 } }];
  card.strokeWeight = 1;
  const band = figma.createRectangle();
  band.resize(128, 6);
  band.cornerRadius = 12;
  band.fills = [{ type: 'SOLID', color: tint }];
  card.appendChild(band);
  const ct = figma.createText();
  ct.characters = cardTitle;
  ct.fontSize = 11;
  ct.x = 10;
  ct.y = 16;
  ct.fills = [{ type: 'SOLID', color: { r: 0.1, g: 0.11, b: 0.14 } }];
  const ow = figma.createText();
  ow.characters = owner;
  ow.fontSize = 9;
  ow.x = 10;
  ow.y = 52;
  ow.fills = [{ type: 'SOLID', color: { r: 0.45, g: 0.47, b: 0.54 } }];
  card.appendChild(ct);
  card.appendChild(ow);
  canvas.appendChild(card);
}
milestone(64, 'Q1', 'Feb', 'Design parity', 'Team Tokens', { r: 0.78, g: 0.88, b: 1 });
milestone(198, 'Q2', 'May', 'API hardening', 'Platform', { r: 0.88, g: 0.95, b: 0.86 });
milestone(332, 'Q3', 'Aug', 'Enterprise GA', 'GTM', { r: 0.95, g: 0.88, b: 1 });
root.appendChild(canvas);
return { rootId: root.id };
