await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
function createAutoLayout(direction) {
  if (typeof figma.createAutoLayout === 'function') {
    return figma.createAutoLayout(direction);
  }
  const frame = figma.createFrame();
  frame.layoutMode = direction === 'VERTICAL' ? 'VERTICAL' : 'HORIZONTAL';
  return frame;
}
const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const wrap = createAutoLayout('VERTICAL');
wrap.resize(440, 310);
wrap.x = 20;
wrap.y = 24;
wrap.itemSpacing = 14;
const top = createAutoLayout('HORIZONTAL');
top.resize(440, 40);
top.primaryAxisAlignItems = 'SPACE_BETWEEN';
top.counterAxisAlignItems = 'CENTER';
const brand = figma.createText();
brand.characters = 'Northwind Analytics';
brand.fontSize = 17;
brand.fills = [{ type: 'SOLID', color: { r: 0.07, g: 0.09, b: 0.14 } }];
const chip = createAutoLayout('HORIZONTAL');
chip.paddingLeft = 12;
chip.paddingRight = 12;
chip.paddingTop = 7;
chip.paddingBottom = 7;
chip.cornerRadius = 16;
chip.counterAxisAlignItems = 'CENTER';
chip.fills = [{ type: 'SOLID', color: { r: 0.94, g: 0.95, b: 0.98 } }];
chip.strokes = [{ type: 'SOLID', color: { r: 0.86, g: 0.88, b: 0.93 } }];
chip.strokeWeight = 1;
const chipT = figma.createText();
chipT.characters = 'Last 7 days';
chipT.fontSize = 11;
chipT.fills = [{ type: 'SOLID', color: { r: 0.32, g: 0.34, b: 0.42 } }];
chip.appendChild(chipT);
top.appendChild(brand);
top.appendChild(chip);
wrap.appendChild(top);
const cards = createAutoLayout('HORIZONTAL');
cards.resize(440, 108);
cards.itemSpacing = 10;
function kpi(title, value, delta, up) {
  const card = createAutoLayout('VERTICAL');
  card.resize(140, 108);
  card.paddingTop = 12;
  card.paddingLeft = 12;
  card.paddingRight = 12;
  card.paddingBottom = 12;
  card.itemSpacing = 10;
  card.cornerRadius = 12;
  card.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
  card.effects = [{ type: 'DROP_SHADOW', color: { r: 0.12, g: 0.2, b: 0.45, a: 0.12 }, offset: { x: 0, y: 6 }, radius: 14, blendMode: 'NORMAL', visible: true }];
  const t0 = figma.createText();
  t0.characters = title;
  t0.fontSize = 10;
  t0.fills = [{ type: 'SOLID', color: { r: 0.45, g: 0.47, b: 0.55 } }];
  const t1 = figma.createText();
  t1.characters = value;
  t1.fontSize = 22;
  t1.fills = [{ type: 'SOLID', color: { r: 0.08, g: 0.1, b: 0.16 } }];
  const pill = createAutoLayout('HORIZONTAL');
  pill.paddingLeft = 8;
  pill.paddingRight = 8;
  pill.paddingTop = 4;
  pill.paddingBottom = 4;
  pill.cornerRadius = 8;
  pill.counterAxisAlignItems = 'CENTER';
  pill.fills = [{ type: 'SOLID', color: up ? { r: 0.9, g: 0.98, b: 0.93 } : { r: 1, g: 0.93, b: 0.93 } }];
  const pt = figma.createText();
  pt.characters = delta;
  pt.fontSize = 10;
  pt.fills = [{ type: 'SOLID', color: up ? { r: 0.1, g: 0.52, b: 0.38 } : { r: 0.75, g: 0.18, b: 0.2 } }];
  pill.appendChild(pt);
  card.appendChild(t0);
  card.appendChild(t1);
  card.appendChild(pill);
  return card;
}
cards.appendChild(kpi('Active trials', '1,284', '+6.4%', true));
cards.appendChild(kpi('Conversion', '3.9%', '+0.3pt', true));
cards.appendChild(kpi('Churn', '0.8%', '-0.1pt', true));
wrap.appendChild(cards);
const chartShell = createAutoLayout('VERTICAL');
chartShell.resize(440, 140);
chartShell.paddingTop = 14;
chartShell.paddingLeft = 14;
chartShell.paddingRight = 14;
chartShell.paddingBottom = 14;
chartShell.itemSpacing = 10;
chartShell.cornerRadius = 14;
chartShell.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
chartShell.strokes = [{ type: 'SOLID', color: { r: 0.88, g: 0.9, b: 0.94 } }];
chartShell.strokeWeight = 1;
const capT = figma.createText();
capT.characters = 'Engagement Index';
capT.fontSize = 12;
capT.fills = [{ type: 'SOLID', color: { r: 0.22, g: 0.24, b: 0.3 } }];
chartShell.appendChild(capT);
const bars = createAutoLayout('HORIZONTAL');
bars.resize(400, 72);
bars.itemSpacing = 6;
bars.counterAxisAlignItems = 'MAX';
const hVals = [28, 44, 36, 58, 42, 66, 52];
const warm = [{ r: 0.95, g: 0.65, b: 0.38 }, { r: 0.98, g: 0.72, b: 0.42 }, { r: 0.92, g: 0.55, b: 0.34 }, { r: 0.96, g: 0.62, b: 0.4 }, { r: 0.94, g: 0.58, b: 0.36 }, { r: 0.99, g: 0.75, b: 0.45 }, { r: 0.9, g: 0.52, b: 0.33 }];
for (let i = 0; i < 7; i++) {
  const bar = figma.createRectangle();
  bar.resize(44, hVals[i]);
  bar.cornerRadius = 8;
  bar.fills = [{ type: 'SOLID', color: warm[i] }];
  bars.appendChild(bar);
}
chartShell.appendChild(bars);
const foot = figma.createText();
foot.characters = 'Mon     Tue     Wed     Thu     Fri     Sat     Sun';
foot.fontSize = 9;
foot.fills = [{ type: 'SOLID', color: { r: 0.55, g: 0.56, b: 0.62 } }];
chartShell.appendChild(foot);
wrap.appendChild(chartShell);
root.appendChild(wrap);
return { rootId: root.id };
