/** Readable Plugin API keys to export per node type (exhaustive subset). */
const COMMON: readonly string[] = [
  'visible',
  'locked',
  'opacity',
  'blendMode',
  'rotation',
  'effects',
  'effectStyleId',
  'exportSettings',
  'reactions',
  'constraints',
  'layoutPositioning',
  'layoutSizingHorizontal',
  'layoutSizingVertical',
  'layoutAlign',
  'layoutGrow',
  'explicitVariableModes',
  'boundVariables',
  /** Wired on component / instance sublayers (TEXT, FRAME, nested INSTANCE, …). */
  'componentPropertyReferences',
  'isMask',
  'maskType',
  'expanded',
];

const GEOMETRY: readonly string[] = [
  ...COMMON,
  'x',
  'y',
  'width',
  'height',
  'fills',
  'fillStyleId',
  'strokes',
  'strokeStyleId',
  'strokeWeight',
  'strokeAlign',
  'strokeCap',
  'strokeJoin',
  'miterLimit',
  'dashPattern',
  'individualStrokeWeights',
  'cornerRadius',
  'topLeftRadius',
  'topRightRadius',
  'bottomRightRadius',
  'bottomLeftRadius',
  'cornerSmoothing',
  'absoluteTransform',
  'relativeTransform',
];

export const PROPERTY_KEYS_BY_TYPE: Record<string, readonly string[]> = {
  DOCUMENT: ['visible', 'locked'],
  PAGE: [
    ...COMMON,
    'backgrounds',
    'fills',
    'guides',
    'selection',
    'isPageDivider',
    'devStatus',
    'flowStartingPoints',
  ],
  FRAME: [
    ...GEOMETRY,
    'backgrounds',
    'clipsContent',
    'layoutMode',
    'primaryAxisSizingMode',
    'counterAxisSizingMode',
    'primaryAxisAlignItems',
    'counterAxisAlignItems',
    'counterAxisAlignContent',
    'paddingLeft',
    'paddingRight',
    'paddingTop',
    'paddingBottom',
    'itemSpacing',
    'counterAxisSpacing',
    'layoutWrap',
    'layoutGrids',
    'gridStyleId',
    'gridRowCount',
    'gridColumnCount',
    'gridRowGap',
    'gridColumnGap',
    'gridRowSizes',
    'gridColumnSizes',
    'itemReverseZIndex',
    'strokesIncludedInLayout',
    'overflowDirection',
    'numberOfFixedChildren',
  ],
  GROUP: [...COMMON, 'absoluteTransform', 'relativeTransform'],
  TRANSFORM_GROUP: [...COMMON, 'absoluteTransform', 'relativeTransform'],
  SECTION: [...GEOMETRY, 'sectionContentsHidden', 'devStatus'],
  SLICE: [...COMMON, 'exportSettings'],
  RECTANGLE: GEOMETRY,
  ELLIPSE: [...GEOMETRY, 'arcData'],
  LINE: [...GEOMETRY, 'strokeCap', 'strokeJoin'],
  POLYGON: [...GEOMETRY, 'pointCount'],
  STAR: [...GEOMETRY, 'pointCount', 'innerRadius'],
  VECTOR: [...GEOMETRY, 'vectorPaths', 'handleMirroring'],
  BOOLEAN_OPERATION: [...GEOMETRY, 'booleanOperation'],
  TEXT: [
    ...GEOMETRY,
    'characters',
    'fontSize',
    'fontName',
    'fontWeight',
    'textAlignHorizontal',
    'textAlignVertical',
    'textAutoResize',
    'textTruncation',
    'maxLines',
    'lineHeight',
    'letterSpacing',
    'paragraphIndent',
    'paragraphSpacing',
    'listSpacing',
    'hangingPunctuation',
    'hangingList',
    'listOptions',
    'textStyleId',
    'styledSegments',
    'textDecoration',
    'textCase',
    'leadingTrim',
    'openTypeFeatures',
    'hyperlink',
    'textOnPath',
  ],
  COMPONENT: [...GEOMETRY, 'description', 'remote', 'key', 'componentPropertyDefinitions'],
  COMPONENT_SET: [
    ...GEOMETRY,
    'description',
    'remote',
    'key',
    'componentPropertyDefinitions',
    'defaultVariant',
  ],
  INSTANCE: [
    ...GEOMETRY,
    'mainComponent',
    'componentProperties',
    'overrides',
    'scaleFactor',
    'clipsContent',
  ],
  TABLE: [...COMMON, 'tableNodeSize'],
  TABLE_CELL: [...GEOMETRY, 'rowIndex', 'columnIndex'],
  STICKY: [...GEOMETRY, 'authorVisible', 'description'],
  CONNECTOR: [...COMMON, 'connectorLineType', 'connectorStart', 'connectorEnd', 'strokeWeight'],
  SHAPE_WITH_TEXT: [...GEOMETRY, 'characters', 'fontSize', 'fontName'],
  WIDGET: [...COMMON, 'widgetSyncedState'],
  CODE_BLOCK: [...GEOMETRY, 'code', 'codeLanguage'],
  MEDIA: [...GEOMETRY, 'mediaData'],
  EMBED: [...GEOMETRY, 'embedData'],
  LINK_UNFURL: [...GEOMETRY, 'linkUnfurlData'],
  HIGHLIGHT: GEOMETRY,
  WASHI_TAPE: GEOMETRY,
  STAMP: GEOMETRY,
  SLIDE: [...GEOMETRY, 'slideNodeSize'],
  TEXT_PATH: [...GEOMETRY, 'characters', 'fontSize'],
};

export function keysForNodeType(type: string): readonly string[] {
  return PROPERTY_KEYS_BY_TYPE[type] ?? COMMON;
}
