await figma.loadFontAsync({ family: 'Inter', style: 'Regular' });
function createAutoLayout(direction) {
  if (typeof figma.createAutoLayout === 'function') {
    return figma.createAutoLayout(direction);
  }
  const frame = figma.createFrame();
  frame.layoutMode = direction === 'VERTICAL' ? 'VERTICAL' : 'HORIZONTAL';
  return frame;
}
const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const panel = createAutoLayout('VERTICAL');
panel.resize(424, 322);
panel.x = 28;
panel.y = 18;
panel.itemSpacing = 10;
panel.cornerRadius = 16;
panel.fills = [{ type: 'SOLID', color: { r: 0.98, g: 0.98, b: 0.995 } }];
panel.strokes = [{ type: 'SOLID', color: { r: 0.88, g: 0.9, b: 0.93 } }];
panel.strokeWeight = 1;
panel.paddingTop = 12;
panel.paddingLeft = 12;
panel.paddingRight = 12;
panel.paddingBottom = 12;
const toolbar = createAutoLayout('HORIZONTAL');
toolbar.resize(400, 40);
toolbar.primaryAxisAlignItems = 'SPACE_BETWEEN';
toolbar.counterAxisAlignItems = 'CENTER';
const crumbs = figma.createText();
crumbs.characters = 'Team drive  /  Product  /  Research';
crumbs.fontSize = 12;
crumbs.fills = [{ type: 'SOLID', color: { r: 0.18, g: 0.2, b: 0.26 } }];
const icons = createAutoLayout('HORIZONTAL');
icons.itemSpacing = 8;
for (let i = 0; i < 3; i++) {
  const sq = figma.createRectangle();
  sq.resize(28, 28);
  sq.cornerRadius = 8;
  sq.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
  sq.strokes = [{ type: 'SOLID', color: { r: 0.88, g: 0.9, b: 0.93 } }];
  sq.strokeWeight = 1;
  icons.appendChild(sq);
}
toolbar.appendChild(crumbs);
toolbar.appendChild(icons);
panel.appendChild(toolbar);
const quick = createAutoLayout('HORIZONTAL');
quick.itemSpacing = 8;
function qchip(l) {
  const c = createAutoLayout('HORIZONTAL');
  c.paddingLeft = 10;
  c.paddingRight = 10;
  c.paddingTop = 6;
  c.paddingBottom = 6;
  c.cornerRadius = 12;
  c.counterAxisAlignItems = 'CENTER';
  c.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
  const t = figma.createText();
  t.characters = l;
  t.fontSize = 10;
  t.fills = [{ type: 'SOLID', color: { r: 0.35, g: 0.38, b: 0.46 } }];
  c.appendChild(t);
  return c;
}
quick.appendChild(qchip('Shared with me'));
quick.appendChild(qchip('Recent'));
quick.appendChild(qchip('Starred'));
panel.appendChild(quick);
const folderStrip = createAutoLayout('HORIZONTAL');
folderStrip.itemSpacing = 10;
for (let i = 0; i < 3; i++) {
  const fd = createAutoLayout('VERTICAL');
  fd.resize(80, 72);
  fd.paddingTop = 8;
  fd.primaryAxisAlignItems = 'CENTER';
  fd.itemSpacing = 6;
  fd.cornerRadius = 12;
  fd.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
  const icon = figma.createRectangle();
  icon.resize(36, 28);
  icon.cornerRadius = 6;
  icon.fills = [{ type: 'SOLID', color: { r: 0.92, g: 0.78, b: 0.42, a: 1 } }];
  const nm = figma.createText();
  nm.characters = i === 0 ? 'Interviews' : i === 1 ? 'Insights' : 'Archive';
  nm.fontSize = 9;
  nm.fills = [{ type: 'SOLID', color: { r: 0.32, g: 0.34, b: 0.4 } }];
  fd.appendChild(icon);
  fd.appendChild(nm);
  folderStrip.appendChild(fd);
}
panel.appendChild(folderStrip);
const list = createAutoLayout('VERTICAL');
list.resize(400, 152);
list.itemSpacing = 6;
list.cornerRadius = 12;
list.paddingTop = 8;
list.paddingLeft = 8;
list.paddingRight = 8;
list.paddingBottom = 8;
list.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
function fileRow(nm, typ, tint) {
  const r = createAutoLayout('HORIZONTAL');
  r.resize(384, 36);
  r.paddingLeft = 8;
  r.paddingRight = 8;
  r.cornerRadius = 9;
  r.primaryAxisAlignItems = 'SPACE_BETWEEN';
  r.counterAxisAlignItems = 'CENTER';
  r.fills = [{ type: 'SOLID', color: { r: 0.99, g: 0.995, b: 1 } }];
  const left = createAutoLayout('HORIZONTAL');
  left.itemSpacing = 8;
  left.counterAxisAlignItems = 'CENTER';
  const ic = figma.createRectangle();
  ic.resize(22, 22);
  ic.cornerRadius = 6;
  ic.fills = [{ type: 'SOLID', color: tint }];
  const t = figma.createText();
  t.characters = nm;
  t.fontSize = 11;
  t.fills = [{ type: 'SOLID', color: { r: 0.15, g: 0.16, b: 0.22 } }];
  left.appendChild(ic);
  left.appendChild(t);
  const pill = createAutoLayout('HORIZONTAL');
  pill.paddingLeft = 8;
  pill.paddingRight = 8;
  pill.paddingTop = 4;
  pill.paddingBottom = 4;
  pill.cornerRadius = 10;
  pill.counterAxisAlignItems = 'CENTER';
  pill.fills = [{ type: 'SOLID', color: { r: 0.94, g: 0.95, b: 0.99 } }];
  const pt = figma.createText();
  pt.characters = typ;
  pt.fontSize = 9;
  pt.fills = [{ type: 'SOLID', color: { r: 0.4, g: 0.42, b: 0.5 } }];
  pill.appendChild(pt);
  r.appendChild(left);
  r.appendChild(pill);
  return r;
}
list.appendChild(fileRow('Vision deck.fig', 'Design', { r: 0.85, g: 0.9, b: 1 }));
list.appendChild(fileRow('Research-rollups.csv', 'Sheet', { r: 0.88, g: 0.96, b: 0.9 }));
list.appendChild(fileRow('Playback-notes.md', 'Doc', { r: 0.94, g: 0.92, b: 1 }));
panel.appendChild(list);
root.appendChild(panel);
return { rootId: root.id };
