const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const grid = figma.createFrame();
grid.resize(340, 200);
grid.x = 70;
grid.y = 80;
grid.layoutMode = 'GRID';
grid.gridRowCount = 2;
grid.gridColumnCount = 3;
grid.gridRowGap = 8;
grid.gridColumnGap = 8;
grid.gridRowSizes = [{ type: 'FIXED', value: 56 }, { type: 'FIXED', value: 120 }];
grid.gridColumnSizes = [{ type: 'FLEX', value: 1 }, { type: 'FLEX', value: 1 }, { type: 'FLEX', value: 1 }];
grid.fills = [{ type: 'SOLID', color: { r: 1, g: 1, b: 1 } }];
root.appendChild(grid);
const hero = figma.createRectangle();
hero.resize(120, 80);
hero.fills = [{ type: 'SOLID', color: { r: 0.2, g: 0.45, b: 0.95 } }];
hero.cornerRadius = 8;
grid.appendChildAt(hero, 0, 0);
hero.gridRowSpan = 2;
hero.gridColumnSpan = 2;
const side = figma.createRectangle();
side.resize(60, 40);
side.fills = [{ type: 'SOLID', color: { r: 0.35, g: 0.75, b: 0.55 } }];
side.cornerRadius = 6;
grid.appendChildAt(side, 0, 2);
const foot = figma.createRectangle();
foot.resize(80, 32);
foot.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.55, b: 0.2 } }];
foot.cornerRadius = 6;
grid.appendChildAt(foot, 1, 2);
foot.setGridChildPosition(1, 2);
return { rootId: root.id };
