const root = figma.createFrame();
root.name = 'ScenarioRoot';
root.resize(480, 360);
root.fills = [{ type: 'SOLID', color: { r: 0.95, g: 0.96, b: 0.98 } }];
figma.currentPage.appendChild(root);
const row = figma.createAutoLayout();
row.resize(400, 48);
row.x = 40;
row.y = 156;
row.itemSpacing = 0;
const left = figma.createRectangle();
left.resize(80, 40);
left.layoutSizingHorizontal = 'FILL';
left.fills = [{ type: 'SOLID', color: { r: 0.2, g: 0.6, b: 0.9 } }];
const spacer = figma.createRectangle();
spacer.resize(24, 40);
spacer.fills = [{ type: 'SOLID', color: { r: 0.75, g: 0.77, b: 0.82 } }];
const right = figma.createRectangle();
right.resize(80, 40);
right.layoutSizingHorizontal = 'FILL';
right.fills = [{ type: 'SOLID', color: { r: 0.2, g: 0.75, b: 0.35 } }];
row.appendChild(left);
row.appendChild(spacer);
row.appendChild(right);
root.appendChild(row);
return { rootId: root.id };
